# Generated by Django 5.0.1 on 2026-03-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_worker_badge_history'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workerbadgehistory',
            new_name='Badge_Histo_worker__dfe0e9_idx',
            old_name='Badge_Histo_worker__629be2_idx',
        ),
        migrations.RenameIndex(
            model_name='workerbadgehistory',
            new_name='Badge_Histo_worker__75d4ad_idx',
            old_name='Badge_Histo_worker__fc0594_idx',
        ),
    ]
