# Generated by Django 5.0.1 on 2026-03-31 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_citizen_temp_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
